version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=false
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m
    depends_on:
      zookeeper:
        condition: service_healthy
  app:
    build: .
    container_name: atomicseats-app
    environment:
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - kafka
    command: sh -c "node server.js"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  booking-worker:
    build: .
    container_name: booking-worker
    environment:
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - kafka
    command: sh -c "node src/worker/bookingConsumer.js"
    volumes:
      - .:/usr/src/app